In [1]:
import numpy as np
import pandas as pd
from os.path import join, dirname, isfile, basename
from os import getcwd, listdir

In [4]:
oil = pd.read_csv('ooip.csv')

In [2]:
eastings = [ 
    4700,
    4700,
    57000,
    58000,
    59000,
    60000,
    61000,
    62000,
    63000,
    64000,
]
northings = [
    400,
    800,
    10000,
    8000,
    12000,
    10000,
    8000,
    12000,
    10000,
    8000,
]

In [5]:
step = oil['northing'][1]-oil['northing'][0]

In [14]:
well_length = 5280
c = []
for e, n in zip(eastings, northings):
    c.append(np.power(10, oil.loc[(oil['northing']-step <= n) & (n <= oil['northing']+step ) & (oil['easting'] >= e) & 
                  (oil['easting'] <= e+well_length)]['OOIP'].values).sum())

In [15]:
s = 0
for x in c:
    s+=x

In [24]:
s

609230.4458484785

In [22]:
t = (s *24 *  50) / 1.6

In [23]:
t * 0.15

68538425.15795383

In [30]:
for e, n in zip(eastings, northings):
    print(np.power(oil.loc[(oil['northing']-step <= n) & (n <= oil['northing']+step ) & (oil['easting'] >= e) & 
                  (oil['easting'] <= e+well_length)].values, 10))

[[5.25991322e+36 1.04857600e+26 1.71362111e+04]
 [5.25991322e+36 1.07187761e+27 1.71362111e+04]
 [6.49250621e+36 1.04857600e+26 1.71362111e+04]
 [6.49250621e+36 1.07187761e+27 1.71362111e+04]
 [7.97922663e+36 1.04857600e+26 1.69189394e+04]
 [7.97922663e+36 1.07187761e+27 1.69189394e+04]
 [9.76562500e+36 1.04857600e+26 1.69189394e+04]
 [9.76562500e+36 1.07187761e+27 1.69189394e+04]
 [1.19042424e+37 1.04857600e+26 1.69189394e+04]
 [1.19042424e+37 1.07187761e+27 1.69189394e+04]
 [1.44555106e+37 1.04857600e+26 1.60233522e+04]
 [1.44555106e+37 1.07187761e+27 1.60233522e+04]
 [1.74887470e+37 1.04857600e+26 1.68409697e+04]
 [1.74887470e+37 1.07187761e+27 1.68409697e+04]
 [2.10832519e+37 1.04857600e+26 1.65482544e+04]
 [2.10832519e+37 1.07187761e+27 1.65482544e+04]
 [2.53295162e+37 1.04857600e+26 1.65482544e+04]
 [2.53295162e+37 1.07187761e+27 1.65482544e+04]
 [3.03305489e+37 1.04857600e+26 1.65482544e+04]
 [3.03305489e+37 1.07187761e+27 1.65482544e+04]
 [3.62033331e+37 1.04857600e+26 1.654825

In [3]:
data_address = join(dirname(getcwd()), "mapping")
all_data = pd.read_csv(join(data_address, "all_data.csv"))

In [56]:
p_a = []
o_a = []
for e, n in zip(eastings, northings):
    rows = all_data.loc[(oil['northing']-step <= n) & (n <= oil['northing']+step ) & (oil['easting'] >= e) & 
                  (oil['easting'] <= e+well_length)]
    p_a.append(rows['porosity'].mean())
    o_a.append(rows['oil saturation'].mean() - 0.0005)


In [57]:
p_a

[0.05491959559654294,
 0.05491959559654294,
 0.08555223715044585,
 0.08641471473469801,
 0.08728942737546119,
 0.08817161068903186,
 0.08867490447436374,
 0.08848605065314252,
 0.08837876039163713,
 0.08827147013013177]

In [58]:
o_a

[0.9995,
 0.9995,
 0.9297431428127835,
 0.9258136699880715,
 0.9184833629967912,
 0.907690538673359,
 0.8960797640699281,
 0.8838979833321057,
 0.8728476336050571,
 0.862259323597936]

In [59]:
for o, p, e, n in zip(o_a, p_a, eastings, northings):
    print("Well originating at: {}E, {}N, porosity average: {}, oil saturation average:{}".format(
    e,n,p,n))

Well originating at: 4700E, 400N, porosity average: 0.05491959559654294, oil saturation average:400
Well originating at: 4700E, 800N, porosity average: 0.05491959559654294, oil saturation average:800
Well originating at: 57000E, 10000N, porosity average: 0.08555223715044585, oil saturation average:10000
Well originating at: 58000E, 8000N, porosity average: 0.08641471473469801, oil saturation average:8000
Well originating at: 59000E, 12000N, porosity average: 0.08728942737546119, oil saturation average:12000
Well originating at: 60000E, 10000N, porosity average: 0.08817161068903186, oil saturation average:10000
Well originating at: 61000E, 8000N, porosity average: 0.08867490447436374, oil saturation average:8000
Well originating at: 62000E, 12000N, porosity average: 0.08848605065314252, oil saturation average:12000
Well originating at: 63000E, 10000N, porosity average: 0.08837876039163713, oil saturation average:10000
Well originating at: 64000E, 8000N, porosity average: 0.0882714701301